#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Reload the shell
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias zshrc="vim ~/.zshrc && reload"
alias ccs-gerrit="cd ~/Documents/code/ccs-gerrit"

# Reload .zprofile
source ~/.zprofile

# For Tmux
DISABLE_AUTO_TITLE=true

source /usr/local/share/zsh/site-functions/_aws

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
